name: Build en DEV_JBCR

on:
  push:
    branches:
      - DEV_EBCD

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      with:
        repository: EstrellaBelen/TallerGITHUB
        ref: DEV_EBCD

    - name: Build with Maven
      run: mvn -B package --file hola-mundo/pom.xml
